In [1]:
from pydataset import data
from math import sqrt
import pandas as pd
import numpy as np
np.random.seed(29)

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
first_die = np.random.choice([1,2,3,4,5,6], size = 1_000_000)
second_die = np.random.choice([1,2,3,4,5,6], size = 1_000_000)
first_die, second_die

(array([6, 4, 5, ..., 4, 4, 6]), array([3, 5, 3, ..., 3, 4, 2]))

In [4]:
first_die == second_die

array([False, False, False, ..., False,  True, False])

In [5]:
(first_die == second_die).mean()

0.166725

In [6]:
# 2. If you flip 8 coins, what is the probability of getting 
# exactly 3 heads? What is the probability of getting more 
# than 3 heads?

In [7]:
n_simulations = 1_000_000
n_trials = 8
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size =(n_simulations, n_trials))
flips

sum_of_flips = flips.sum(axis=1)
(sum_of_flips == 3).mean()

0.219366

In [8]:
(sum_of_flips > 3).mean() 


0.636552

In [9]:
# 3. There are approximitely 3 web development cohorts 
# for every 1 data science cohort at Codeup. Assuming that Codeup 
# randomly selects an alumni to put on a billboard, what are the 
# odds that the two billboards I drive past both 
# have data science students on them?

In [10]:
sim = 1_000_000
trials = 2
data = 1
web = 0
commutes = np.random.choice ([data, web], size=(sim, trials), p=[0.25, 0.75]) 

prob = (commutes.sum(axis=1) == 2).mean()

prob

0.062867

In [11]:
Theoretical = (1/4) * (1/4)
Theoretical

0.0625

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages with a
# standard deviation of 1.5 a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on Friday
# afternoon? (Remember, if you have mean and standard deviation, 
# use the np.random.normal) You'll need to make a judgement call on 
# how to handle some of your values

In [13]:
avg_pop = 3 
pop_std = 1.5
sim = 1_000_000
trials = 5
simulation = np.random.normal(avg_pop, pop_std, size=(sim, trials)) 
simulation

array([[3.22182126, 3.38124611, 2.19373835, 2.56731035, 4.07713537],
       [4.77704863, 1.75817619, 4.04759536, 2.90605825, 1.15753488],
       [3.71720704, 5.6113371 , 2.48997328, 2.80643954, 4.39020263],
       ...,
       [2.94118854, 2.09985034, 3.53036865, 1.93245781, 3.78698001],
       [2.1608775 , 1.8824481 , 4.28786043, 6.25147458, 5.65536202],
       [2.6651122 , 3.5980215 , 3.63924165, 4.67945752, 2.55272916]])

In [14]:
probablity= (simulation.sum(axis=1) < 17).mean()
probablity

0.724502

In [15]:
# 5. Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use
# np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the
# likelihood the woman is taller than the man?

In [16]:
men = 178
mstd = 8
women = 170
wstd = 6

s_men = np.random.normal(men, mstd, 1_000_000)
s_men

s_women = np.random.normal(women, wstd, 1_000_000)
s_women

calculated_prob = (s_women > s_men).mean()
calculated_prob

0.212631

In [17]:
# 6. When installing anaconda on a student's computer, there's a 
# 1 in 250 chance that the download is corrupted and the 
# installation fails. What are the odds that after having 50 
# students download anaconda, no one has an installation issue? 
# 100 students?

# A .What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# B .How likely is it that 450 students all download anaconda without 
# an issue?



In [18]:
sim = 1_000_000
trials = 50 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.182209

In [19]:
sim = 1_000_000
trials = 100 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.330833

In [20]:
# A.
sim = 1_000_000
trials = 150 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.451438

In [21]:
# B. 
sim = 1_000_000
trials = 450 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
1 - prob

0.16487600000000002

In [22]:
# 7. There's a 70% chance on any given day that there will be at 
# least one food truck at Travis Park. However, you haven't
# seen a food truck there in 3 days. How unlikely is this?

# A.  How likely is it that a food truck will show up sometime this week?

In [36]:
sim = 1_000_000
trials = 3
ft = 1
noft = 0

simulation = np.random.choice([noft, ft], size = (sim, trials), p = [0.30, 0.70]) 

prob = (simulation.sum(axis = 1) == 0).mean()
prob

0.026885

In [41]:
# A.
sim = 1_000_000
trials = 7
ft = 1
noft = 0
simulation = np.random.choice([ft, noft], size = (sim, trials), p = [0.70, 0.30])
prob = (simulation.sum(axis = 1) == 0).mean()
1- prob

0.999801

In [25]:
# 8. If 23 people are in the same room, what are the odds that two
# of them share a birthday? What if it's 20 people? 40?

In [26]:
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations for same birth days(Birthday Paradox)
n_trials = 23
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
len(simulation[0])
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 23]
combo_bday = np.array(combo_bday)
combo_bday.mean()

21.659334179970973

In [27]:
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations 
n_trials = 20
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 20]
combo_bday = np.array(combo_bday)
combo_bday.mean()

18.756562508363565

In [28]:
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations 
n_trials = 40
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
combo_bday.mean()
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 40]
combo_bday = np.array(combo_bday)
combo_bday.mean()

37.68360162376376